[package]
name = "jstz_api"
authors.workspace = true
version.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
boa_engine = "0.17.0"
boa_gc = "0.17.0"
tezos-smart-rollup-host = "0.2.1"
derive_more = "0.99.17"
jstz_core.workspace = true
jstz_crypto.workspace = true
jstz_ledger.workspace = true
