[workspace]
members = ["jstz_core", "jstz_api", "jstz_ledger", "jstz_crypto", "jstz_kernel"]

[workspace.package]
edition = "2021"
version = "0.1.0"
authors = ["TriliTech <concat@trili.tech>"]
repository = "https://github.com/trilitech/jstz"

[workspace.dependencies]
jstz_core = { path = "jstz_core" }
jstz_api = { path = "jstz_api" }
jstz_kernel = { path = "jstz_kernel" }
jstz_ledger = { path = "jstz_ledger" }
jstz_crypto = { path = "jstz_crypto" }

[patch.crates-io]
tezos-smart-rollup = { git = "https://gitlab.com/tezos/tezos.git", branch = "ajob410@sdk-ord-paths" }
tezos-smart-rollup-core = { git = "https://gitlab.com/tezos/tezos.git", branch = "ajob410@sdk-ord-paths" }
tezos-smart-rollup-debug = { git = "https://gitlab.com/tezos/tezos.git", branch = "ajob410@sdk-ord-paths" }
tezos-smart-rollup-encoding = { git = "https://gitlab.com/tezos/tezos.git", branch = "ajob410@sdk-ord-paths" }
tezos-smart-rollup-entrypoint = { git = "https://gitlab.com/tezos/tezos.git", branch = "ajob410@sdk-ord-paths" }
tezos-smart-rollup-host = { git = "https://gitlab.com/tezos/tezos.git", branch = "ajob410@sdk-ord-paths" }
tezos-smart-rollup-storage = { git = "https://gitlab.com/tezos/tezos.git", branch = "ajob410@sdk-ord-paths" }
